//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingUxLib.Resources.Values {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackingUxLib.Resources.Values.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Expiration.
        /// </summary>
        public static string AccountExpirationDate {
            get {
                return ResourceManager.GetString("AccountExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been blocked..
        /// </summary>
        public static string AccountIsBlocked {
            get {
                return ResourceManager.GetString("AccountIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Account.
        /// </summary>
        public static string ActiveAccount {
            get {
                return ResourceManager.GetString("ActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error accurred communication to the server. Please try again..
        /// </summary>
        public static string ApiErrorMessage {
            get {
                return ResourceManager.GetString("ApiErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotMum.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Tracking Solution.
        /// </summary>
        public static string AppNameDesc {
            get {
                return ResourceManager.GetString("AppNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Number.
        /// </summary>
        public static string CenterNumber {
            get {
                return ResourceManager.GetString("CenterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Server.
        /// </summary>
        public static string ChangeServer {
            get {
                return ResourceManager.GetString("ChangeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Device.
        /// </summary>
        public static string ConfigTerminal {
            get {
                return ResourceManager.GetString("ConfigTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To the Device.
        /// </summary>
        public static string ConnectToTerminal {
            get {
                return ResourceManager.GetString("ConnectToTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Contact Name.
        /// </summary>
        public static string Contact1Name {
            get {
                return ResourceManager.GetString("Contact1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Contact Namt.
        /// </summary>
        public static string Contact2Name {
            get {
                return ResourceManager.GetString("Contact2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Contact Name.
        /// </summary>
        public static string Contact3Name {
            get {
                return ResourceManager.GetString("Contact3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Contact Name.
        /// </summary>
        public static string Contact4Name {
            get {
                return ResourceManager.GetString("Contact4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5th Contact Name.
        /// </summary>
        public static string Contact5Name {
            get {
                return ResourceManager.GetString("Contact5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user.
        /// </summary>
        public static string DearUser {
            get {
                return ResourceManager.GetString("DearUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the device failed. Please make sure the device is ON and connected to the network..
        /// </summary>
        public static string DeviceNotConnectedMessage {
            get {
                return ResourceManager.GetString("DeviceNotConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Application.
        /// </summary>
        public static string DownloadApplication {
            get {
                return ResourceManager.GetString("DownloadApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Device.
        /// </summary>
        public static string EditTerminal {
            get {
                return ResourceManager.GetString("EditTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error accurred connecting to the server. Please try again..
        /// </summary>
        public static string ErrorConnectingToTheServer {
            get {
                return ResourceManager.GetString("ErrorConnectingToTheServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMessageBoxCaption {
            get {
                return ResourceManager.GetString("ErrorMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Reset.
        /// </summary>
        public static string FactoryReset {
            get {
                return ResourceManager.GetString("FactoryReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure for reseting to the factory settings?.
        /// </summary>
        public static string FactoryResetWarning {
            get {
                return ResourceManager.GetString("FactoryResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fence.
        /// </summary>
        public static string Fence {
            get {
                return ResourceManager.GetString("Fence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Device Version Command.
        /// </summary>
        public static string GetVersionCommand {
            get {
                return ResourceManager.GetString("GetVersionCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input password is invalid..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Validity.
        /// </summary>
        public static string InitialValidity {
            get {
                return ResourceManager.GetString("InitialValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input all required fields..
        /// </summary>
        public static string InputRequiredFields {
            get {
                return ResourceManager.GetString("InputRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input email is invalid..
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number has incorrect format..
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is invalid..
        /// </summary>
        public static string InvalidPasswordConfirm {
            get {
                return ResourceManager.GetString("InvalidPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile number is invalid..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input port number is invalid..
        /// </summary>
        public static string InvalidPortNumber {
            get {
                return ResourceManager.GetString("InvalidPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input device ID is invalid..
        /// </summary>
        public static string InvalidTerminalID {
            get {
                return ResourceManager.GetString("InvalidTerminalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is invalid..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language and Time Zone.
        /// </summary>
        public static string LanguageAndTimeZone {
            get {
                return ResourceManager.GetString("LanguageAndTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Activity Time.
        /// </summary>
        public static string LastActivityTime {
            get {
                return ResourceManager.GetString("LastActivityTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Battery SMS.
        /// </summary>
        public static string LowBatterySms {
            get {
                return ResourceManager.GetString("LowBatterySms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Low Battery SMS.
        /// </summary>
        public static string LowBatterySmsStatusText {
            get {
                return ResourceManager.GetString("LowBatterySmsStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string MakeCall {
            get {
                return ResourceManager.GetString("MakeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Command.
        /// </summary>
        public static string MakeCallCommand {
            get {
                return ResourceManager.GetString("MakeCallCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer / Device ID.
        /// </summary>
        public static string Manufacturer_DeviceID {
            get {
                return ResourceManager.GetString("Manufacturer_DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketer.
        /// </summary>
        public static string Marketer {
            get {
                return ResourceManager.GetString("Marketer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Message.
        /// </summary>
        public static string MessageBoxCaption {
            get {
                return ResourceManager.GetString("MessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer.
        /// </summary>
        public static string NewCustomer {
            get {
                return ResourceManager.GetString("NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device.
        /// </summary>
        public static string NewTerminal {
            get {
                return ResourceManager.GetString("NewTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimitted.
        /// </summary>
        public static string NoLimitAccount {
            get {
                return ResourceManager.GetString("NoLimitAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Month.
        /// </summary>
        public static string OneMonthAccount {
            get {
                return ResourceManager.GetString("OneMonthAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Year.
        /// </summary>
        public static string OneYearAccount {
            get {
                return ResourceManager.GetString("OneYearAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number.
        /// </summary>
        public static string PortNumber {
            get {
                return ResourceManager.GetString("PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Off Command.
        /// </summary>
        public static string PowerOffCommand {
            get {
                return ResourceManager.GetString("PowerOffCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you turned it off, you wouldn&apos;t be able to turn it on remotely. Are you sure?.
        /// </summary>
        public static string PowerOffWarning {
            get {
                return ResourceManager.GetString("PowerOffWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kid Watch.
        /// </summary>
        public static string product_kids_watch {
            get {
                return ResourceManager.GetString("product_kids_watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q50.
        /// </summary>
        public static string product_model_q50 {
            get {
                return ResourceManager.GetString("product_model_q50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string product_model_variant_black {
            get {
                return ResourceManager.GetString("product_model_variant_black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string product_model_variant_blue {
            get {
                return ResourceManager.GetString("product_model_variant_blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string product_model_variant_pink {
            get {
                return ResourceManager.GetString("product_model_variant_pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string product_model_variant_yellow {
            get {
                return ResourceManager.GetString("product_model_variant_yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State / City.
        /// </summary>
        public static string Province_City {
            get {
                return ResourceManager.GetString("Province_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string QuestionMessageBoxCaption {
            get {
                return ResourceManager.GetString("QuestionMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Removal Alarm.
        /// </summary>
        public static string RemoveAlarm {
            get {
                return ResourceManager.GetString("RemoveAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Removal SMS.
        /// </summary>
        public static string RemoveAlarmSms {
            get {
                return ResourceManager.GetString("RemoveAlarmSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send watch removal SMS to the center number.
        /// </summary>
        public static string RemoveAlarmSmsStatusText {
            get {
                return ResourceManager.GetString("RemoveAlarmSmsStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send watch removal alarm.
        /// </summary>
        public static string RemoveAlarmStatusText {
            get {
                return ResourceManager.GetString("RemoveAlarmStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required..
        /// </summary>
        public static string RequiredUserName {
            get {
                return ResourceManager.GetString("RequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Command.
        /// </summary>
        public static string RestartCommand {
            get {
                return ResourceManager.GetString("RestartCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route History.
        /// </summary>
        public static string RouteHistory {
            get {
                return ResourceManager.GetString("RouteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Time.
        /// </summary>
        public static string SaveTime {
            get {
                return ResourceManager.GetString("SaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second(s).
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file.
        /// </summary>
        public static string SelectFileRequired {
            get {
                return ResourceManager.GetString("SelectFileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select .wav file.
        /// </summary>
        public static string SelectWavFile {
            get {
                return ResourceManager.GetString("SelectWavFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Command.
        /// </summary>
        public static string SendCommand {
            get {
                return ResourceManager.GetString("SendCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Command.
        /// </summary>
        public static string SendCommandToTerminal {
            get {
                return ResourceManager.GetString("SendCommandToTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flower Command.
        /// </summary>
        public static string SendFlowersCommand {
            get {
                return ResourceManager.GetString("SendFlowersCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Message Command.
        /// </summary>
        public static string SendMessageCommand {
            get {
                return ResourceManager.GetString("SendMessageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Message Command.
        /// </summary>
        public static string SendVoiceCommand {
            get {
                return ResourceManager.GetString("SendVoiceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:Port.
        /// </summary>
        public static string Server_Port {
            get {
                return ResourceManager.GetString("Server_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Months.
        /// </summary>
        public static string SixMonthAccount {
            get {
                return ResourceManager.GetString("SixMonthAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS SMS.
        /// </summary>
        public static string SmsToSOS {
            get {
                return ResourceManager.GetString("SmsToSOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SOS SMS.
        /// </summary>
        public static string SmsToSOSStatusText {
            get {
                return ResourceManager.GetString("SmsToSOSStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st SOS Number.
        /// </summary>
        public static string Sos1 {
            get {
                return ResourceManager.GetString("Sos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd SOS Number.
        /// </summary>
        public static string Sos2 {
            get {
                return ResourceManager.GetString("Sos2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd SOS Number.
        /// </summary>
        public static string Sos3 {
            get {
                return ResourceManager.GetString("Sos3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS Numbers.
        /// </summary>
        public static string SosNumbers {
            get {
                return ResourceManager.GetString("SosNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statements.
        /// </summary>
        public static string Statements {
            get {
                return ResourceManager.GetString("Statements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string SubscriberPanel {
            get {
                return ResourceManager.GetString("SubscriberPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Devices.
        /// </summary>
        public static string SubscriberTerminals {
            get {
                return ResourceManager.GetString("SubscriberTerminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successfull done..
        /// </summary>
        public static string SuccessfullyDone {
            get {
                return ResourceManager.GetString("SuccessfullyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tehran.
        /// </summary>
        public static string Tehran {
            get {
                return ResourceManager.GetString("Tehran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Configuration.
        /// </summary>
        public static string TerminalConfiguration {
            get {
                return ResourceManager.GetString("TerminalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Contacts.
        /// </summary>
        public static string TerminalContacts {
            get {
                return ResourceManager.GetString("TerminalContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Password.
        /// </summary>
        public static string TerminalPassword {
            get {
                return ResourceManager.GetString("TerminalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Terminals {
            get {
                return ResourceManager.GetString("Terminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Termial.
        /// </summary>
        public static string TerminalSearch {
            get {
                return ResourceManager.GetString("TerminalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of devices.
        /// </summary>
        public static string TerminalsPageDesc {
            get {
                return ResourceManager.GetString("TerminalsPageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Device.
        /// </summary>
        public static string TestTerminal {
            get {
                return ResourceManager.GetString("TestTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Months.
        /// </summary>
        public static string ThreeMonthAccount {
            get {
                return ResourceManager.GetString("ThreeMonthAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Tracking {
            get {
                return ResourceManager.GetString("Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Interval.
        /// </summary>
        public static string UploadInterval {
            get {
                return ResourceManager.GetString("UploadInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant.
        /// </summary>
        public static string Variant {
            get {
                return ResourceManager.GetString("Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotMum.
        /// </summary>
        public static string WebConstantTitle {
            get {
                return ResourceManager.GetString("WebConstantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
