//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackAdmin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackAdmin.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ozTracker.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Logs.
        /// </summary>
        public static string CommandLogs {
            get {
                return ResourceManager.GetString("CommandLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Payload.
        /// </summary>
        public static string CommandPayload {
            get {
                return ResourceManager.GetString("CommandPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Set.
        /// </summary>
        public static string CommandSet {
            get {
                return ResourceManager.GetString("CommandSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Type.
        /// </summary>
        public static string CommandType {
            get {
                return ResourceManager.GetString("CommandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker Config.
        /// </summary>
        public static string ConfigTracker {
            get {
                return ResourceManager.GetString("ConfigTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAR-MONTH-DAY.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Icon Name.
        /// </summary>
        public static string DefaultIcon {
            get {
                return ResourceManager.GetString("DefaultIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Empty Resul}.
        /// </summary>
        public static string ExecutionResultEmpty {
            get {
                return ResourceManager.GetString("ExecutionResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statements.
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @2021 All rights reserved for zorrotracker.com.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Name.
        /// </summary>
        public static string GivenName {
            get {
                return ResourceManager.GetString("GivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Data.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string Monitoring {
            get {
                return ResourceManager.GetString("Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Model.
        /// </summary>
        public static string ProductModel {
            get {
                return ResourceManager.GetString("ProductModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Tracker.
        /// </summary>
        public static string ProductType_cartracker {
            get {
                return ResourceManager.GetString("ProductType_cartracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids Watch.
        /// </summary>
        public static string ProductType_kidswatch {
            get {
                return ResourceManager.GetString("ProductType_kidswatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawID.
        /// </summary>
        public static string RawID {
            get {
                return ResourceManager.GetString("RawID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Data.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Trackers.
        /// </summary>
        public static string SearchTrackers {
            get {
                return ResourceManager.GetString("SearchTrackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Users.
        /// </summary>
        public static string SearchUsers {
            get {
                return ResourceManager.GetString("SearchUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Commands.
        /// </summary>
        public static string SendingCommands {
            get {
                return ResourceManager.GetString("SendingCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show On Map.
        /// </summary>
        public static string ShowOnMap {
            get {
                return ResourceManager.GetString("ShowOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation done successfully..
        /// </summary>
        public static string SuccessfullyDone {
            get {
                return ResourceManager.GetString("SuccessfullyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Lab.
        /// </summary>
        public static string TestLab {
            get {
                return ResourceManager.GetString("TestLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker ID.
        /// </summary>
        public static string TrackerId {
            get {
                return ResourceManager.GetString("TrackerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker Information.
        /// </summary>
        public static string TrackerInfo {
            get {
                return ResourceManager.GetString("TrackerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker Logs.
        /// </summary>
        public static string TrackerLogs {
            get {
                return ResourceManager.GetString("TrackerLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker Messages.
        /// </summary>
        public static string TrackerMessages {
            get {
                return ResourceManager.GetString("TrackerMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackers.
        /// </summary>
        public static string Trackers {
            get {
                return ResourceManager.GetString("Trackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information Form.
        /// </summary>
        public static string UserInformationForm {
            get {
                return ResourceManager.GetString("UserInformationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
