export const ALREADY_ADDED = "ALREADY_ADDED";
export const NOT_ALLOWED = "NOT_ALLOWED";
export const TRACKER_OFFLINE = "TRACKER_OFFLINE";
export const TRACKER_NO_REPLY = "NO_REPLY_FROM_TRACKER";
export const CONTACTS_FULL = "CONTACTS_FULL";