
export const FORGOTTEN_PASSWORD_SCREEN = 'FORGOTTEN_PASSWORD_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const HOME_CONTAINER = 'HOME_CONTAINER';
export const HOME_LOGIN_SWITCH = 'HOME_LOGIN_SWITCH';
export const HOME_SCREEN = 'HOME_SCREEN';
export const MAP_SCREEN = 'MAP_SCREEN';
export const MESSAGES_SCREEN = 'MESSAGES_SCREEN';
export const NOTIFICATIONS_SCREEN = 'NOTIFICATIONS_SCREEN';
export const TRACKERS_SCREEN = 'TRACKERS_SCREEN';
export const ADD_TRACKER = "ADD_TRACKER";
export const CONFIG_TRACKER = "CONFIG_TRACKER";
export const QR_CODE_SCREEN = "QR_CODE_SCREEN";
export const ALLOW_USER_SCREEN = "ALLOW_USER_SCREEN";
export const PERMITTED_USERS_SCREEN = "PERMITTED_USERS_SCREEN";
export const COMMAND_SCREEN = "COMMAND_SCREEN";