// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackDataAccess.Database;

namespace TrackDataAccess.Migrations
{
    [DbContext(typeof(TrackDbContext))]
    [Migration("20201120122118_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TrackDataAccess.Models.Terminal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("AddTime")
                        .HasColumnName("add_time")
                        .HasColumnType("datetime");

                    b.Property<int?>("AssociatedProductId")
                        .HasColumnName("associated_product_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeleteTime")
                        .HasColumnName("delete_time")
                        .HasColumnType("datetime");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnName("device_type")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32);

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("is_deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastConnectedServer")
                        .HasColumnName("last_connected_server")
                        .HasColumnType("varchar(32)")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("LastConnection")
                        .HasColumnName("last_connection")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("terminals");
                });
#pragma warning restore 612, 618
        }
    }
}
